# Generated by Django 2.2 on 2019-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=200, verbose_name='question')),
                ('question_de', models.CharField(max_length=200, verbose_name='question')),
                ('answer_en', models.CharField(max_length=200, verbose_name='answer')),
                ('answer_de', models.CharField(max_length=200, verbose_name='answer')),
            ],
        ),
    ]
