# Generated by Django 2.2 on 2019-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_de',
            field=models.CharField(max_length=200, verbose_name='Answer Verbose Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_en',
            field=models.CharField(max_length=200, verbose_name='Answer Verbose Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_de',
            field=models.CharField(max_length=200, verbose_name='Question Verbose Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, verbose_name='Question Verbose Name'),
        ),
    ]
